Repository cisagov/con-pca-api, pull requests merged in 2021-06, with the labels that each got.

#239 CPD-159 Create subscription before launching
  src/api/utils/subscription/actions.py
  src/api/views/subscription_views.py
  src/auth/views.py
Labels: enhancement

#240 CPD-166 Use subscription uuid for cisa-phish header
  src/api/utils/subscription/actions.py
  src/api/utils/subscription/campaigns.py
Labels: enhancement

#241 Cycle Report Manual Set Time
  src/api/serializers/subscriptions_serializers.py
  src/api/utils/subscription/actions.py
  src/api/utils/subscription/subscriptions.py
  src/lambda_functions/tasks/process_tasks.py
  tests/api/utils/susbscription/test_subscriptions.py
  tests/lambda_functions/test_tasks.py
Labels: enhancement

#242 Define websockets version
  requirements.txt
Labels: bug

#245 CPD-170 Stop Email
  src/api/utils/subscription/actions.py
Labels: enhancement

#247 Update requirements file
  requirements.txt
Labels: dependencies

#249 Fix cisa-phish header value in start email
  src/api/notifications.py
  src/templates/emails/subscription_started.html
  src/templates/emails/subscription_started.txt
Labels: bug

#253 Download subscription data as JSON
  src/api/urls.py
  src/api/views/subscription_views.py
  src/api/views/template_views.py
Labels: enhancement

#254 Allow for Deletion of Templates
  src/api/views/template_views.py
  tests/api/views/template_views/test_template_view.py
Labels: enhancement

#257 Fix bug when templates selected doesn't exist
  src/api/views/template_views.py
Labels: bug
